# --- Configuración de Seguridad y Red ---
listen_addresses = '*' # Se limita mediante las redes internas de Docker Compose

# --- Ajustes de Memoria Optimizados para Contenedores ---
max_connections = 100
shared_buffers = 128MB
effective_cache_size = 384MB
maintenance_work_mem = 32MB
checkpoint_completion_target = 0.9
wal_buffers = 4MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 1310kB
huge_pages = off
min_wal_size = 80MB
max_wal_size = 1GB

# --- Cumplimiento del Pilar de Logs Limpios ---
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_min_messages = warning
log_min_error_statement = error
# Impide que Postgres guarde las consultas SQL crudas en texto plano si fallan, protegiendo los blobs
log_statement = 'none'